### ISSUE TITLE
Ensure wiki documentation doesn't contain references to Gitter

### ISSUE THREAD

**Issue by m-dombrowski** [enarx/rfcs#32]
As the project transitions to Rocket.Chat, references to Gitter should be updated in documentation. (eg How To Contribute Wiki page)

Thanks @axelsimon for guidance!

**Comment by axelsimon** [comment]
Just checked, there are no mentions of gitter in the wiki:
```
grep -i "gitter" enarx.wiki/*
```
returns nothing.
Closing this one.
